### ISSUE TITLE
interface for alpha-beta algorithm

### ISSUE THREAD

**Issue by psakuru** [psakuru/alpha-beta#1]
In the original algorithm we passed in a vertex to the algorithm function along with the boost graph. During the discussion we thought we can just pass in the game_tree object and call get_current_vertex. However, as we call the function recursively, we need to pass in the next vertex from the children vertices.

Option 1: overload the function. Then we will have two functions.

Option 2: convert to vertex from reference to a pointer and default it to nullptr.

Option 3: just implement the algorithm as we implemented it originally and the end user should pass both game_tree and current_vertex(merged this option for now).

**Comment by chaitu236** [comment]
I think I will overload the functions, one with just game_tree as argument and another with game_tree and vertex as arguments.

**Comment by psakuru** [comment]
Cool...will do the change

**Comment by psakuru** [comment]
75377a4532bea260a09163390ea1b0100598c602
